version: '3.9'
services:
  nodetest:
    container_name: nodetest
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    build:
      context: .
      dockerfile: ./docker/golang.Dockerfile
    restart: 'always'
    ports:
      - "12345:3000"
    volumes:
      - nodetest:/app/storages
      - /nte/storage:/filestorage
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  nodetest:
    name: nodetest
